<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            'Afganistán',
            'Albania',
            'Argelia',
            'Andorra',
            'Angola',
            'Antigua y Barbuda',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Azerbaiyán',
            'Bahamas',
            'Baréin',
            'Bangladés',
            'Barbados',
            'Bielorrusia',
            'Bélgica',
            'Belice',
            'Benín',
            'Bután',
            'Bolivia',
            'Bosnia y Herzegovina',
            'Botsuana',
            'Brasil',
            'Brunéi',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cabo Verde',
            'Camboya',
            'Camerún',
            'Canadá',
            'Chad',
            'Chile',
            'China',
            'Chipre',
            'Colombia',
            'Comoras',
            'Corea del Norte',
            'Corea del Sur',
            'Costa de Marfil',
            'Costa Rica',
            'Croacia',
            'Cuba',
            'Dinamarca',
            'Dominica',
            'Ecuador',
            'Egipto',
            'El Salvador',
            'Emiratos Árabes Unidos',
            'Eritrea',
            'Eslovaquia',
            'Eslovenia',
            'España',
            'Estados Unidos',
            'Estonia',
            'Esuatini',
            'Etiopía',
            'Filipinas',
            'Finlandia',
            'Fiyi',
            'Francia',
            'Gabón',
            'Gambia',
            'Georgia',
            'Ghana',
            'Granada',
            'Grecia',
            'Guatemala',
            'Guinea',
            'Guinea-Bisáu',
            'Guinea Ecuatorial',
            'Guyana',
            'Haití',
            'Honduras',
            'Hungría',
            'India',
            'Indonesia',
            'Irak',
            'Irán',
            'Irlanda',
            'Islandia',
            'Islas Marshall',
            'Islas Salomón',
            'Israel',
            'Italia',
            'Jamaica',
            'Japón',
            'Jordania',
            'Kazajistán',
            'Kenia',
            'Kirguistán',
            'Kiribati',
            'Kuwait',
            'Laos',
            'Lesoto',
            'Letonia',
            'Líbano',
            'Liberia',
            'Libia',
            'Liechtenstein',
            'Lituania',
            'Luxemburgo',
            'Macedonia del Norte',
            'Madagascar',
            'Malasia',
            'Malaui',
            'Maldivas',
            'Malí',
            'Malta',
            'Marruecos',
            'Mauricio',
            'Mauritania',
            'México',
            'Micronesia',
            'Moldavia',
            'Mónaco',
            'Mongolia',
            'Montenegro',
            'Mozambique',
            'Namibia',
            'Nauru',
            'Nepal',
            'Nicaragua',
            'Níger',
            'Nigeria',
            'Noruega',
            'Nueva Zelanda',
            'Omán',
            'Países Bajos',
            'Pakistán',
            'Palaos',
            'Panamá',
            'Papúa Nueva Guinea',
            'Paraguay',
            'Perú',
            'Polonia',
            'Portugal',
            'Catar',
            'Reino Unido',
            'República Centroafricana',
            'República Checa',
            'República del Congo',
            'República Democrática del Congo',
            'República Dominicana',
            'Ruanda',
            'Rumanía',
            'Rusia',
            'Samoa',
            'San Cristóbal y Nieves',
            'San Marino',
            'San Vicente y las Granadinas',
            'Santa Lucía',
            'Santo Tomé y Príncipe',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leona',
            'Singapur',
            'Siria',
            'Somalia',
            'Sri Lanka',
            'Sudáfrica',
            'Sudán',
            'Sudán del Sur',
            'Suecia',
            'Suiza',
            'Surinam',
            'Tailandia',
            'Tanzania',
            'Tayikistán',
            'Timor Oriental',
            'Togo',
            'Tonga',
            'Trinidad y Tobago',
            'Túnez',
            'Turkmenistán',
            'Turquía',
            'Tuvalu',
            'Ucrania',
            'Uganda',
            'Uruguay',
            'Uzbekistán',
            'Vanuatu',
            'Vaticano',
            'Venezuela',
            'Vietnam',
            'Yemen',
            'Yibuti',
            'Zambia',
            'Zimbabue',
        ];

        if (!Country::all()->count()) {
            foreach ($countries as $countryName) {
                $country = new Country(['name' => $countryName]);
                $country->save();
            }
        }
    }
}
