services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend_soccer
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_soccer
      MYSQL_USER: backend_soccer
      MYSQL_PASSWORD: backend_soccer
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
